version: '2'
services:
    yikatong-app:
        image: yikatong
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://yikatong-mysql:3306/yikatong?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    yikatong-mysql:
        extends:
            file: mysql.yml
            service: yikatong-mysql
